name: integration

on:
  push:
    branches:
      - master
  schedule:
    - cron: "23 16 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1

      - name: Install yrs
        run: go install --tags fts5 github.com/miquelruiz/yrs/cmd/yrs@latest

      - name: Subscribe to some channels
        run: |
          ~/go/bin/yrs subscribe-yt https://www.youtube.com/user/wintergatan2000
          ~/go/bin/yrs subscribe-yt https://www.youtube.com/channel/UCMrMVIBtqFW6O0-MWq26gqw

      - name: List channels
        run: |
          ~/go/bin/yrs list-channels | grep -i wintergatan
          ~/go/bin/yrs list-channels | grep -i mechanics

      - name: List videos
        run: |
          num_lines=$(~/go/bin/yrs list-videos | wc -l)
          [[ $num_lines -gt 10 ]]

      - name: Update
        run: |
          ~/go/bin/yrs update
