name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Generate
        run: go generate ./...

      - name: Build
        run: go build --tags fts5,cgo ./...

      - name: Test
        run: go test --tags fts5,cgo -v ./...
